### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by edwardhallgren** [lindell/home-assistant-tv4-play#12]
Trying to start nyhetsmorgon and gets following error. 

`2022-11-15 08:36:47.504 ERROR (MainThread) [homeassistant.components.script.starta_nyhetsmorgon_tv] Starta Nyhetsmorgon på TV: Error executing script. Unexpected error for call_service at pos 1: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/tv4_play/__init__.py", line 31, in play_suggested
    video_url = await hass.async_add_executor_job(get_video_url, suggested_episode)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tv4_play/video_url_fetch/video_fetch.py", line 13, in get_video_url
    data = get(url, headers=headers).json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by nolenjohan** [comment]
It doesn't work for me either, when trying to start TV4 Nyhetsmorgon via a script from HA I receive the error message:

"Failed to call service tv4_play/play_suggested. Expecting value: line 1 column 1 (char 0)"

Script:
![image](https://user-images.githubusercontent.com/34334118/201865166-8c1f69cc-c962-41f7-9749-2dc59d20abee.png)

**Comment by lindell** [comment]
Can you please check if #13 fixes this?

**Comment by edwardhallgren** [comment]
Thanks! working for me!

**Comment by lindell** [comment]
Great! Should now be accessible through HACS and similar.
